### ISSUE TITLE
foundation gem seems broken

### ISSUE THREAD

**Issue by WnP** [zurb/foundation#6261]
```sh
scl@harp test % ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
scl@harp test % npm --version
1.4.28
scl@harp test % bower --version
1.3.12
scl@harp test % grunt --version
grunt-cli v0.1.13
scl@harp test % sass --version
Sass 3.4.11 (Selective Steve)
scl@harp test % compass --version
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2015 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
scl@harp test % git --version
git version 2.2.1
scl@harp test % foundation new test_project
Creating ./test_project
      create  test_project
Cloning into 'test_project'...
remote: Counting objects: 117, done.
remote: Total 117 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (117/117), 40.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (46/46), done.
Checking connectivity... done.
Installing dependencies with bower...
/home/scl/.gem/ruby/2.2.0/gems/foundation-1.0.4/lib/foundation/cli/generator.rb:131:in `read': No such file or directory @ rb_sysopen - /home/scl/test/test_project/bower_components/foundation/scss/foundation/_settings.scss (Errno::ENOENT)
        from /home/scl/.gem/ruby/2.2.0/gems/foundation-1.0.4/lib/foundation/cli/generator.rb:131:in `block (2 levels) in new'
        from /home/scl/.gem/ruby/2.2.0/gems/foundation-1.0.4/lib/foundation/cli/generator.rb:131:in `open'
        from /home/scl/.gem/ruby/2.2.0/gems/foundation-1.0.4/lib/foundation/cli/generator.rb:131:in `block in new'
        from /home/scl/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `block in inside'
        from /usr/lib64/ruby/2.2.0/fileutils.rb:127:in `chdir'
        from /usr/lib64/ruby/2.2.0/fileutils.rb:127:in `cd'
        from /home/scl/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `inside'
        from /home/scl/.gem/ruby/2.2.0/gems/foundation-1.0.4/lib/foundation/cli/generator.rb:128:in `new'
        from /home/scl/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/scl/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/scl/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/scl/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/scl/.gem/ruby/2.2.0/gems/foundation-1.0.4/bin/foundation:4:in `<top (required)>'
        from /home/scl/.gem/ruby/2.2.0/bin/foundation:23:in `load'
        from /home/scl/.gem/ruby/2.2.0/bin/foundation:23:in `<main>'
```

What's wrong in my configuration?
is there some special version to use?

The file `_settings.scss ` is in this folder:

```
scl@harp test % ll test_project/scss
total 4.0K
-rw-r--r-- 1 scl scl    0 Feb  6 14:00 _settings.scss
-rw-r--r-- 1 scl scl 1.5K Feb  6 14:00 app.scss
```
and there's not `scss` folder in `/home/scl/test/test_project/bower_components/foundation/`
Why?

**Comment by WnP** [comment]
here is a simple bash script which works for me:
```sh
#!/usr/bin/env bash
app_name=$1
git clone --depth=1 https://github.com/zurb/foundation-libsass-template.git $app_name
pushd $app_name
cat <<- EOF > bower.json
{ 
  "name": "foundation-libsass-template",
  "dependencies": {
    "foundation": "git@github.com:zurb/bower-foundation.git"
  }
}
EOF
bower install
cp bower_components/foundation/scss/foundation/_settings.scss scss
npm install
grunt build
```
running `this_script.sh project_name` works as `foundation new project_name --libsass`

**Comment by gakimball** [comment]
Strange, so the Bower install of Foundation was just missing the settings file? But when you install the dependencies by hand the file is there?

**Comment by WnP** [comment]
@gakimball the Bower Foundation file is not missing, I just overwrite it to change `"foundation": "zurb/bower-foundation"` to `"foundation": "git@github.com:zurb/bower-foundation.git"`, which fix the problem

**Comment by gakimball** [comment]
You can also reference the Bower package directly:

```
"foundation": "~5.5.1"
```

I'm not sure why our libsass template doesn't just reference it directly.

**Comment by WnP** [comment]
using `"foundation": "~5.5.1"` instead of `"foundation": "git@github.com:zurb/bower-foundation.git"` failed, it doesn't provide the `scss` directory in Foundation folder...

**Comment by WnP** [comment]
great ^^

**Comment by gakimball** [comment]
I ran `bower install foundation` and inside the package I see CSS, JS, and Sass folders, along with the `bower.json`. What do you see in the package?

**Comment by WnP** [comment]
I've just ran `bower install foundation`, this is the `tree -d` output:
```
scl@harp test % tree -d bower_components/foundation
bower_components/foundation
├── css
└── js
    └── foundation
```
no Sass or Scss folder, [complete log available here](http://sprunge.us/OOGO)

**Comment by WnP** [comment]
complete `tree -d` output available [here](http://sprunge.us/HYIB)

**Comment by gakimball** [comment]
Can you try `bower cache clean` and then install again?

**Comment by WnP** [comment]
excellent! that works, and the foundation gem works too

thanks a lot @gakimball 

have you an why my bower cache had a wrong version?

**Comment by gakimball** [comment]
We had some hiccups with our last deployment, and Bower likes to cache versions of packages. So it's possible you got a busted version 5.5.1, and after we fixed it Bower wasn't downloading the fixed version, because it was already cached on your machine.
