### ISSUE TITLE
Module ui.router is not available

### ISSUE THREAD

**Issue by kevinhorek** [zurb/foundation#6333]
I have tried my app on Codio and Digital Ocean and when I run npm start most of the site loads but I get this error, everything works locally.

 Uncaught Error: [$injector:modulerr] Failed to instantiate module application due to:
Error: [$injector:modulerr] Failed to instantiate module ui.router due to:
Error: [$injector:nomod] Module 'ui.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.14/$injector/nomod?p0=ui.router
    at http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:655
    at http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:14151
    at ensure (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:13406)
    at seen (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:13919)
    at http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:29149
    at forEach (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:28675)
    at http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:29052
    at forEach (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:28675)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=ui.router&p1=Error…%2Fnancy-santana.codio.io%3A8080%2Fassets%2Fjs%2Ffoundation.js%3A5%3A28675)
    at http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:655
    at http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:29494
    at forEach (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:28675)
    at http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:29052
    at forEach (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:28675)
    at createInjector (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:31932)
    at doBootstrap (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:10255)
    at bootstrap (http://nancy-santana.codio.io:8080/assets/js/foundation.js:5:10784)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=application&p1=Err…%2Fnancy-santana.codio.io%3A8080%2Fassets%2Fjs%2Ffoundation.js%3A5%3A10784)

**Comment by gakimball** [comment]
Could you re-open this on the [Foundation for Apps](https://github.com/zurb/foundation-apps/issues) issue tracker and describe your setup and deploy process in more detail? Thanks :)
