### ISSUE TITLE
Joyride RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tompopovic** [zurb/foundation#6395]
https://github.com/zurb/foundation/commit/f4149e4e07d798cf1fdfc53075346e94cea66eac?diff=split
breaks joyride with the following error on chrome:

```
RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at Function.jQuery.extend.camelCase (jquery/dist/jquery.js:337:45)
    at null.<anonymous> (jquery/dist/jquery.js:3815:23)
    at jQuery.access (jquery/dist/jquery.js:3486:8)
    at jQuery.fn.extend.data (jquery/dist/jquery.js:3813:10)
    at Object.Foundation.libs.joyride.set_next_tip (foundation/js/foundation/foundation.joyride.js:448:31)
    at Object.Foundation.libs.joyride.set_li (foundation/js/foundation/foundation.joyride.js:432:14)
    at Object.Foundation.libs.joyride.show (foundation/js/foundation/foundation.joyride.js:301:16)
    at Object.Foundation.libs.joyride.show (foundation/js/foundation/foundation.joyride.js:390:16)
    at Object.Foundation.libs.joyride.show (foundation/js/foundation/foundation.joyride.js:390:16)
```

Sample Code:
```
<div id="fistStop">First Stop</div>

<div id="secondStop">Second Stop</div>

<div id="lastStop">Last Stop</div>

<ol class="joyride-list" data-joyride>
  <li data-id="firstStop" data-text="Next" data-options="tip_location: top; prev_button: false">
    <h4>Stop #1</h4>
  </li>
  <li data-id="secondStop" data-text="Next" data-prev-text="Prev">
    <h4>Stop #2</h4> 
  </li>
  <li data-id="lastStop" data-button="Next" data-prev-text="Prev">
    <h4>Stop #3</h4>    
  </li>
</ol>
```

**Comment by tompopovic** [comment]
just noticed i had a typo at id="firstStop" 

still possibly a potential issue when using joyride with one tip and no corresponding ID
