### ISSUE TITLE
unable to run npm start Exit Status 1

### ISSUE THREAD

**Issue by osalama7** [zurb/foundation#6460]
C:\xxxx\xxxx\xxxx\myhtml\myApp>npm start

> foundation-apps-template@1.1.0 start C:\xxxx\xxxx\xxxx\myhtml\myApp
> gulp

[18:51:19] Using gulpfile C:\xxxx\xxxx\www\myhtml\myApp\gulpfile.js
[18:51:19] Starting 'build'...
[18:51:19] Starting 'clean'...
[18:51:19] Finished 'clean' after 62 ms
[18:51:19] Starting 'copy'...
[18:51:19] Starting 'copy:foundation'...
[18:51:19] Finished 'copy:foundation' after 111 ms
[18:51:19] Starting 'sass'...
[18:51:19] Starting 'uglify:foundation'...
[18:51:19] Starting 'uglify:app'...
[18:51:20] Finished 'copy' after 356 ms
[18:51:20] Finished 'uglify:app' after 63 ms
[18:51:20] Finished 'sass' after 572 ms
[18:51:20] Finished 'uglify:foundation' after 426 ms
[18:51:20] Starting 'uglify'...
[18:51:20] Finished 'uglify' after 3.02 µs
[18:51:20] Starting 'copy:templates'...
[18:51:20] Finished 'copy:templates' after 8.82 ms
[18:51:20] Finished 'build' after 775 ms
[18:51:20] Starting 'server'...
[18:51:21] Webserver started at http://localhost:8080
[18:51:21] Finished 'server' after 185 ms
[18:51:21] Starting 'default'...
[18:51:21] Finished 'default' after 11 ms

... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at net.js:1270:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at net.js:1270:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! foundation-apps-template@1.1.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-apps-template@1.1.0 start script 'gulp'.
npm ERR! This is most likely a problem with the foundation-apps-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundation-apps-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xxx\xxxx\xxxx\myhtml\myApp\npm-debug.log

debug.log file 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart foundation-apps-template@1.1.0
7 info start foundation-apps-template@1.1.0
8 verbose unsafe-perm in lifecycle true
9 info foundation-apps-template@1.1.0 Failed to exec start script
10 verbose stack Error: foundation-apps-template@1.1.0 start: `gulp`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid foundation-apps-template@1.1.0
12 verbose cwd C:\wamp\www\myhtml\myApp
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error foundation-apps-template@1.1.0 start: `gulp`
18 error Exit status 1
19 error Failed at the foundation-apps-template@1.1.0 start script 'gulp'.
19 error This is most likely a problem with the foundation-apps-template package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     gulp
19 error You can get their info via:
19 error     npm owner ls foundation-apps-template
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by osalama7** [comment]
Problem solved, Had to rerun npm start a few times, just a refresher
