### ISSUE TITLE
Problem creating new app with foundation-cli EACCES ~/foundation-apps_3c7d8

### ISSUE THREAD

**Issue by osalama7** [zurb/foundation#6699]
problem trying to create a new app with foundation-cli on ubuntu 14.04 terminal.
It stops while installing dependencies 
    Installing dependencies...

    /usr/local/lib/node_modules/foundation-cli/node_modules/bower/node_modules/q/q.js:155
                throw e;
                      ^ 
    Error: EACCES, open '~/.cache/bower/registry/bower.herokuapp.com/lookup  /foundation-apps_3c7d8'

**Comment by gakimball** [comment]
Could you go into the folder that the CLI created and run `bower install` and see what happens?

**Comment by osalama7** [comment]
same error but issued with bower with some more details


bower foundation-apps#~1.1.0    EACCES EACCES, open '/home/nautilus/.cache/bower/registry/bower.herokuapp.com/lookup/foundation-apps_3c7d8'

Stack trace:
Error: EACCES, open '/home/nautilus/.cache/bower/registry/bower.herokuapp.com/lookup/foundation-apps_3c7d8'

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.37

**Comment by ZachPerkitny** [comment]
Have you tried using the sudo command ?

**Comment by ZachPerkitny** [comment]
Try running it with sudo ?

**Comment by osalama7** [comment]
its not recommended to run foundation-apps new command with sudo.

**Comment by osalama7** [comment]
fixed using npm cache clean, and running sudo chown -R /pathtofolder on restricted directories
